// 「みんなのプラン」の仮データ（公開ルートの投稿がまだ無い間のサンプル）。
// 画面からは直接読まず、src/services/plans/community-plans.ts 経由で取得する（Supabase に切り替えるときはそちらだけを直す）。
import type { CommunityPlan } from "@/services/plans/community-plans";

export const MOCK_COMMUNITY_PLANS: CommunityPlan[] = [
  {
    id: "sapporo-date-no-car",
    area: "札幌",
    title: "車なし1万円デート",
    theme: "デート",
    budgetYen: 10000,
    durationLabel: "約6時間",
    transport: "public_transit",
    stops: ["大通公園", "円山公園", "藻岩山展望台"],
    savedCount: 128,
    image: "tvTower",
    prompt: "札幌で彼女とデートしたい。予算1万円。車なし。",
  },
  {
    id: "otaru-half-day-food",
    area: "小樽",
    title: "半日食べ歩き",
    theme: "グルメ",
    budgetYen: 5000,
    durationLabel: "約4時間",
    transport: "walk",
    stops: ["三角市場", "堺町通り", "小樽運河"],
    savedCount: 96,
    image: "otaruWinter",
    prompt: "小樽で半日、食べ歩きを楽しみたい。車なし。",
  },
  {
    id: "sapporo-rainy-day",
    area: "札幌",
    title: "雨の日でも楽しめる1日",
    theme: "屋内",
    budgetYen: 6000,
    durationLabel: "約7時間",
    transport: "public_transit",
    stops: ["サッポロビール博物館", "ラーメン横丁", "白い恋人パーク"],
    savedCount: 74,
    image: "ramen",
    prompt: "札幌で雨の日でも楽しめる1日のプランを作って。車なし。",
  },
  {
    id: "sapporo-night-view-dinner",
    area: "札幌",
    title: "夜景とディナー",
    theme: "夜景",
    budgetYen: 12000,
    durationLabel: "約4時間",
    transport: "public_transit",
    stops: ["すすきの", "もいわ山ロープウェイ", "藻岩山展望台"],
    savedCount: 153,
    image: "nightView",
    prompt: "札幌で夜景とディナーを楽しみたい。",
  },
  {
    id: "biei-blue-pond-drive",
    area: "美瑛",
    title: "青い池と丘をめぐるドライブ",
    theme: "ドライブ",
    budgetYen: 8000,
    durationLabel: "約8時間",
    transport: "car",
    stops: ["白金 青い池", "白ひげの滝", "四季彩の丘"],
    savedCount: 211,
    image: "bluePond",
    prompt: "札幌から車で美瑛へ。青い池と丘をめぐる日帰りドライブをしたい。",
  },
  {
    id: "biei-flower-fields",
    area: "美瑛",
    title: "花畑をゆっくり歩く半日",
    theme: "自然",
    budgetYen: 4000,
    durationLabel: "約4時間",
    transport: "car",
    stops: ["四季彩の丘", "ぜるぶの丘", "パッチワークの路"],
    savedCount: 67,
    image: "flowerHill",
    prompt: "美瑛で花畑をゆっくり見て回りたい。車あり。半日。",
  },
  {
    id: "toya-sunset-daytrip",
    area: "洞爺湖",
    title: "夕日を見に行く日帰り",
    theme: "自然",
    budgetYen: 9000,
    durationLabel: "約9時間",
    transport: "car",
    stops: ["サイロ展望台", "洞爺湖温泉", "湖畔の遊歩道"],
    savedCount: 58,
    image: "lakeToya",
    prompt: "札幌から車で洞爺湖へ。夕日を見る日帰りプランを作って。",
  },
  {
    id: "otaru-canal-evening-walk",
    area: "小樽",
    title: "運河と夕暮れさんぽ",
    theme: "街歩き",
    budgetYen: 3000,
    durationLabel: "約3時間",
    transport: "walk",
    stops: ["小樽駅", "北一硝子", "小樽運河"],
    savedCount: 89,
    image: "hero",
    prompt: "小樽で夕方から3時間、運河のあたりを歩いて楽しみたい。",
  },
];
