// 「みんなのプラン」「ルート詳細」の仮データ（デザイン確認用のサンプル）。
// 本番のデータではない。実在の投稿・投稿者・評価・いいね数・コメント・旅行者向け情報ではなく、すべて表示確認用の値。
// 画面からは直接読まず、route-plans.ts 経由で取得する。公開ルートの投稿（Supabase の route_posts）に切り替えるときは、このファイルごと外す。
import type { ImageKey } from "./images";
import type { RouteComment, RoutePlan, RouteStop, TravelerInfoItem, TravelerInfoKey } from "./route-plans";

/** 立ち寄り先1件。next は次の立ち寄り先までの移動（最後は省く） */
function stop(
  time: string,
  name: string,
  description: string,
  image: ImageKey | null,
  latitude: number,
  longitude: number,
  next?: [label: string, minutes: number],
): RouteStop {
  return { time, name, description, image, latitude, longitude, next: next ? { label: next[0], minutes: next[1] } : null };
}

const comment = (author: string, postedOn: string, likeCount: number, body: string): RouteComment => ({ author, postedOn, likeCount, body });

const BASE_TRAVELER_INFO: TravelerInfoItem[] = [
  { key: "englishMenu", status: "ok", value: "あり" },
  { key: "englishStaff", status: "caution", value: "場所による" },
  { key: "creditCard", status: "ok", value: "使える" },
  { key: "reservation", status: "ok", value: "不要" },
  { key: "vegetarian", status: "ok", value: "あり" },
  { key: "luggage", status: "caution", value: "やや注意" },
];

/** 基本の内容から、ルートごとに違う項目だけを差し替える */
function travelerInfo(overrides: Partial<Record<TravelerInfoKey, [status: TravelerInfoItem["status"], value: string]>> = {}): TravelerInfoItem[] {
  return BASE_TRAVELER_INFO.map((item) => {
    const override = overrides[item.key];
    return override ? { key: item.key, status: override[0], value: override[1] } : item;
  });
}

export const MOCK_ROUTE_PLANS: RoutePlan[] = [
  {
    id: "kyoto-classic-one-day",
    region: "京都",
    title: "1日でめぐる、京都の定番とちょっとした穴場",
    lead: "はじめての京都でも楽しめる、王道とこだわりのバランスがちょうどいい1日ルートです。カフェや食事、歴史的な景観をゆったりと楽しめます。",
    image: "kyotoYasaka",
    daysLabel: "1日",
    durationLabel: "約8時間",
    budgetYen: 10000,
    transportLabel: "徒歩・電車・バス",
    styles: ["カップル", "友人", "ひとり旅"],
    tags: ["京都", "カフェ", "グルメ", "カップル", "ひとり旅"],
    author: "Emma",
    postedOn: "2026.04.12",
    rating: 4.8,
    reviewCount: 86,
    likeCount: 342,
    stops: [
      stop("09:00", "京都駅", "京都の旅をスタート。駅構内で軽く朝食をとって、まずは嵐山へ向かいます。", "kyotoStation", 34.9858, 135.7588, ["JR嵯峨野線", 15]),
      stop("10:00", "嵐山", "渡月橋や竹林の道を散策。朝の時間は比較的空いていて、ゆっくり楽しめます。", "arashiyamaBamboo", 35.017, 135.6713, ["徒歩", 10]),
      stop("12:30", "嵯峨野でランチ", "地元の食材を使った和食のお店でランチ。落ち着いた雰囲気でゆっくり過ごせます。", "teishoku", 35.0194, 135.6745, ["バス", 40]),
      stop("14:00", "金閣寺", "京都を代表する観光スポット。美しい庭園と金閣の景色は必見です。", "kinkakuji", 35.0394, 135.7292, ["バス", 30]),
      stop("16:00", "清水寺・二年坂", "夕方の時間に清水寺周辺を散策。お土産やカフェも楽しめます。", "kyotoYasaka", 34.9949, 135.785),
    ],
    travelerInfo: travelerInfo(),
    comments: [
      comment("Daniel", "2026.04.15", 24, "The bamboo forest in Arashiyama was amazing. I recommend going early in the morning."),
      comment("Sophie", "2026.04.10", 18, "The lunch restaurant had an English menu and the staff were very kind. It was easy to order."),
      comment("James", "2026.04.08", 12, "Kinkaku-ji was beautiful, especially on a sunny day. It was a bit crowded in the afternoon."),
    ],
    prompt: "京都で1日、定番の寺社とちょっとした穴場をめぐりたい。車なし。予算1万円。",
  },
  {
    id: "tokyo-asakusa-walk",
    region: "東京",
    title: "東京で楽しむ、下町と街歩きの1日",
    lead: "浅草から上野、谷中へ。歩いてまわれる距離に、寺社・市場・カフェがまとまった下町ルートです。",
    image: "tokyoAsakusa",
    daysLabel: "1日",
    durationLabel: "約7時間",
    budgetYen: 8000,
    transportLabel: "徒歩・電車",
    styles: ["ひとり旅", "友人"],
    tags: ["東京", "カフェ", "グルメ", "ひとり旅"],
    author: "Daniel",
    postedOn: "2026.05.02",
    rating: 4.6,
    reviewCount: 64,
    likeCount: 281,
    stops: [
      stop("10:00", "浅草寺・仲見世通り", "雷門から仲見世を抜けて本堂へ。午前中は人が少なく、写真も撮りやすい時間です。", "tokyoAsakusa", 35.7148, 139.7967, ["徒歩", 10]),
      stop("11:30", "かっぱ橋道具街", "包丁や器、食品サンプルの専門店が並ぶ通り。おみやげ探しにも向いています。", null, 35.7137, 139.7886, ["徒歩", 20]),
      stop("13:00", "上野公園", "公園近くでランチのあと、池のまわりを散歩。美術館や博物館にも立ち寄れます。", null, 35.7146, 139.7732, ["電車", 15]),
      stop("15:30", "谷中銀座", "昔ながらの商店街で食べ歩き。路地のカフェでひと休みして1日を締めくくります。", null, 35.7276, 139.7653),
    ],
    travelerInfo: travelerInfo({ englishStaff: ["ok", "多い"], luggage: ["ok", "問題なし"] }),
    comments: [
      comment("Olivia", "2026.05.06", 15, "Senso-ji before 10am was calm and lovely. Most shops on Nakamise had English signs."),
      comment("Liam", "2026.05.03", 9, "Yanaka Ginza is cash only at many stalls, so bring some coins."),
    ],
    prompt: "東京の浅草・上野・谷中を1日で街歩きしたい。車なし。予算8千円。",
  },
  {
    id: "sapporo-gourmet-trip",
    region: "北海道",
    title: "札幌グルメ旅｜海鮮・味噌ラーメン・市場めぐり",
    lead: "朝の市場で海鮮丼、夜は味噌ラーメン。食べることを中心に、札幌の街と夜景も楽しむルートです。",
    image: "kaisendon",
    daysLabel: "2泊3日",
    durationLabel: "約9時間",
    budgetYen: 30000,
    transportLabel: "徒歩・地下鉄・ロープウェイ",
    styles: ["カップル", "友人"],
    tags: ["北海道", "グルメ", "カップル"],
    author: "Sophie",
    postedOn: "2026.02.20",
    rating: 4.9,
    reviewCount: 112,
    likeCount: 417,
    stops: [
      stop("09:00", "二条市場", "朝いちばんに海鮮丼。カニやウニを選べるお店が多く、開店直後は並ばずに入れます。", "kaisendon", 43.0586, 141.3586, ["徒歩", 10]),
      stop("11:00", "大通公園", "テレビ塔を見上げながら公園を散歩。季節のイベントが開かれていることもあります。", "tvTower", 43.06, 141.347, ["地下鉄", 10]),
      stop("18:00", "すすきの・ラーメン横丁", "味噌ラーメンの専門店が並ぶ小さな通り。食券式のお店が多めです。", "ramen", 43.054, 141.3536, ["市電・ロープウェイ", 40]),
      stop("20:00", "藻岩山展望台", "札幌の街を一望できる夜景スポット。山頂は冷えるので上着があると安心です。", "nightView", 43.0224, 141.3222),
    ],
    travelerInfo: travelerInfo({ vegetarian: ["caution", "少なめ"] }),
    comments: [
      comment("Jack", "2026.02.24", 21, "The seafood bowl at Nijo Market was the best meal of our trip. They had picture menus."),
      comment("Mia", "2026.02.22", 11, "The ropeway closes earlier in winter, so check the last departure time."),
    ],
    prompt: "札幌で海鮮と味噌ラーメンを食べ歩きたい。夜景も見たい。車なし。",
  },
  {
    id: "ishigaki-rental-car",
    region: "沖縄",
    title: "レンタカーでめぐる、沖縄の絶景スポット",
    lead: "石垣島を車で一周。展望台と白い砂浜をつなぎながら、海の色を一日中楽しめるルートです。",
    image: "okinawaBeach",
    daysLabel: "2泊3日",
    durationLabel: "約8時間",
    budgetYen: 25000,
    transportLabel: "レンタカー",
    styles: ["カップル", "家族"],
    tags: ["沖縄", "ドライブ", "カップル", "家族旅行"],
    author: "Jack",
    postedOn: "2026.06.18",
    rating: 4.7,
    reviewCount: 58,
    likeCount: 265,
    stops: [
      stop("10:00", "新石垣空港", "空港でレンタカーを受け取って出発。島の東側から北へ向かいます。", null, 24.3964, 124.245, ["車", 25]),
      stop("11:00", "玉取崎展望台", "サンゴ礁の海と半島を見渡せる展望台。駐車場から歩いて数分です。", null, 24.4533, 124.2147, ["車", 30]),
      stop("13:00", "川平湾", "白い砂浜とエメラルド色の海。グラスボートで海の中ものぞけます。", "okinawaBeach", 24.453, 124.145, ["車", 35]),
      stop("17:30", "ユーグレナモール", "市街地のアーケードで夕食とおみやげ探し。島料理のお店が集まっています。", null, 24.3406, 124.1556),
    ],
    travelerInfo: travelerInfo({ reservation: ["caution", "レンタカーは必要"], luggage: ["ok", "車なら問題なし"] }),
    comments: [
      comment("Noah", "2026.06.22", 14, "Driving was easy and parking was free at most viewpoints. Book the rental car early in summer."),
      comment("Ava", "2026.06.20", 8, "Kabira Bay is not for swimming, but the glass-bottom boat was great for kids."),
    ],
    prompt: "石垣島をレンタカーで1日ドライブして、絶景スポットをまわりたい。車あり。",
  },
  {
    id: "kamikochi-mountain-walk",
    region: "長野",
    title: "上高地で過ごす、山と川の1泊2日",
    lead: "大正池から河童橋、明神池へ。高低差の少ない道を歩きながら、穂高連峰の景色を楽しむルートです。",
    image: "kamikochi",
    daysLabel: "1泊2日",
    durationLabel: "約7時間",
    budgetYen: 28000,
    transportLabel: "電車・バス・徒歩",
    styles: ["ひとり旅", "家族"],
    tags: ["ひとり旅", "家族旅行"],
    author: "Olivia",
    postedOn: "2026.07.08",
    rating: 4.8,
    reviewCount: 47,
    likeCount: 198,
    stops: [
      stop("08:00", "松本駅", "電車とバスを乗り継いで上高地へ。マイカーは入れないため、バスの時刻を先に確認しておきます。", null, 36.2308, 137.9644, ["電車・バス", 95]),
      stop("10:00", "大正池", "朝は水面に山が映りやすい時間。ここから川沿いの遊歩道を歩きます。", null, 36.2276, 137.6197, ["徒歩", 60]),
      stop("12:00", "河童橋", "上高地の中心。橋の近くの食堂でランチをとり、穂高連峰を眺めます。", "kamikochi", 36.2493, 137.6379, ["徒歩", 60]),
      stop("14:00", "明神池", "静かな池と神社。木道が整備されていて歩きやすい道です。", null, 36.253, 137.668),
    ],
    travelerInfo: travelerInfo({ creditCard: ["caution", "現金が安心"], luggage: ["caution", "預けてから歩く"] }),
    comments: [
      comment("Lucas", "2026.07.12", 10, "The trail is flat and well marked in English. Bring cash for the bus and small shops."),
      comment("Emma", "2026.07.10", 7, "We left our suitcases at the bus terminal lockers. They fill up by late morning."),
    ],
    prompt: "上高地を1日歩いて、山と川の景色を楽しみたい。車なし。",
  },
  {
    id: "osaka-minami-food-night",
    region: "大阪",
    title: "大阪・ミナミで食べ歩く、にぎやかな夜",
    lead: "市場、路地、ネオンの通りへ。たこ焼きや串カツを少しずつ食べながら、ミナミを歩くルートです。",
    image: "osakaDotonbori",
    daysLabel: "1日",
    durationLabel: "約6時間",
    budgetYen: 6000,
    transportLabel: "徒歩・地下鉄",
    styles: ["友人", "カップル"],
    tags: ["大阪", "グルメ", "カップル"],
    author: "Liam",
    postedOn: "2026.03.14",
    rating: 4.7,
    reviewCount: 93,
    likeCount: 356,
    stops: [
      stop("15:00", "黒門市場", "海鮮やフルーツをその場で食べられる市場。夕方は閉まるお店が多いので早めに。", null, 34.6654, 135.5063, ["徒歩", 8]),
      stop("16:30", "法善寺横丁", "石畳の細い路地。苔に覆われたお不動さんに水をかけてお参りします。", null, 34.6679, 135.5024, ["徒歩", 3]),
      stop("17:30", "道頓堀", "看板とネオンがにぎやかな通りで、たこ焼きやお好み焼きを食べ歩き。", "osakaDotonbori", 34.6687, 135.5013, ["地下鉄", 15]),
      stop("19:30", "通天閣・新世界", "串カツのお店が並ぶ下町。展望台から夜の街を見て1日を締めくくります。", null, 34.6525, 135.5063),
    ],
    travelerInfo: travelerInfo({ englishStaff: ["ok", "多い"], luggage: ["caution", "人が多く注意"] }),
    comments: [
      comment("James", "2026.03.18", 19, "Dotonbori is crowded after 6pm but so much fun. Most takoyaki stands take cards now."),
      comment("Chloe", "2026.03.16", 6, "Kuromon Market closes around 5pm, so do not start too late."),
    ],
    prompt: "大阪のミナミで夕方から食べ歩きをしたい。車なし。予算6千円。",
  },
  {
    id: "fukuoka-dazaifu-hakata",
    region: "福岡",
    title: "太宰府と博多をめぐる、福岡の1日",
    lead: "午前は太宰府でお参りと参道歩き、夜は博多の屋台へ。電車だけで動ける1日ルートです。",
    image: "dazaifu",
    daysLabel: "1日",
    durationLabel: "約8時間",
    budgetYen: 9000,
    transportLabel: "電車・徒歩",
    styles: ["ひとり旅", "友人"],
    tags: ["九州", "グルメ", "カフェ", "ひとり旅"],
    author: "Mia",
    postedOn: "2026.04.26",
    rating: 4.6,
    reviewCount: 51,
    likeCount: 224,
    stops: [
      stop("09:30", "博多駅", "博多駅から電車で太宰府へ。乗り換えは1回です。", null, 33.5897, 130.4207, ["電車", 40]),
      stop("10:30", "太宰府天満宮", "学問の神様をまつる神社。太鼓橋を渡って本殿へ向かいます。", "dazaifu", 33.5215, 130.5349, ["徒歩", 5]),
      stop("12:00", "参道でお茶", "焼きたての梅ヶ枝餅と抹茶でひと休み。参道のカフェも人気です。", null, 33.5197, 130.5322, ["電車", 45]),
      stop("18:00", "中洲の屋台", "川沿いに並ぶ屋台でラーメンや焼き鳥を。席が少ないので早めの時間が入りやすいです。", null, 33.5925, 130.4064),
    ],
    travelerInfo: travelerInfo({ creditCard: ["caution", "屋台は現金"] }),
    comments: [
      comment("Ethan", "2026.04.29", 13, "The yatai stalls were friendly even with little Japanese. Cash only, around 2,000 yen per person."),
      comment("Sophie", "2026.04.27", 5, "Dazaifu is busy on weekends. A weekday morning was perfect."),
    ],
    prompt: "福岡で太宰府と博多の屋台を1日で楽しみたい。車なし。",
  },
  {
    id: "yufuin-onsen-stay",
    region: "大分",
    title: "由布院で温泉と散策、ゆったり1泊2日",
    lead: "由布岳を眺めながら温泉街を歩き、夜は宿の温泉へ。予定を詰めこまない、休むためのルートです。",
    image: "yufuin",
    daysLabel: "1泊2日",
    durationLabel: "約6時間",
    budgetYen: 27000,
    transportLabel: "徒歩",
    styles: ["カップル", "家族"],
    tags: ["九州", "温泉", "カップル", "カフェ"],
    author: "Noah",
    postedOn: "2026.01.30",
    rating: 4.8,
    reviewCount: 77,
    likeCount: 389,
    stops: [
      stop("13:00", "由布院駅", "駅を出ると正面に由布岳。荷物は駅の預かり所から宿へ送れます。", "yufuin", 33.263, 131.3556, ["徒歩", 10]),
      stop("13:30", "湯の坪街道", "雑貨やスイーツのお店が続く通り。食べ歩きをしながら金鱗湖へ向かいます。", null, 33.2664, 131.364, ["徒歩", 15]),
      stop("15:00", "金鱗湖", "温泉が湧く小さな湖。寒い朝には湖面に霧が立ちます。", null, 33.2668, 131.37, ["徒歩", 10]),
      stop("16:30", "温泉宿にチェックイン", "夕食の前に露天風呂へ。貸切風呂のある宿なら家族でも入りやすいです。", null, 33.264, 131.369),
    ],
    travelerInfo: travelerInfo({ reservation: ["caution", "宿は必要"], luggage: ["ok", "宿へ配送できる"] }),
    comments: [
      comment("Ava", "2026.02.03", 17, "Our ryokan had a private bath, which was great because of my tattoo. Ask when you book."),
      comment("Daniel", "2026.02.01", 9, "The luggage delivery from the station to the inn cost a few hundred yen and saved us a lot."),
    ],
    prompt: "由布院で温泉と散策をのんびり楽しみたい。1泊2日。",
  },
  {
    id: "ginzan-onsen-night",
    region: "山形",
    title: "銀山温泉で過ごす、大正ロマンの夜",
    lead: "木造の旅館が並ぶ川沿いの温泉街。ガス灯がともる夕方から夜の景色を楽しむルートです。",
    image: "ginzanOnsen",
    daysLabel: "1泊2日",
    durationLabel: "約5時間",
    budgetYen: 32000,
    transportLabel: "電車・バス・徒歩",
    styles: ["カップル", "ひとり旅"],
    tags: ["温泉", "カップル", "ひとり旅"],
    author: "Ava",
    postedOn: "2026.01.12",
    rating: 4.9,
    reviewCount: 39,
    likeCount: 276,
    stops: [
      stop("14:00", "大石田駅", "新幹線の駅からバスで温泉街へ。本数が少ないので時刻表を確認しておきます。", null, 38.5943, 140.3724, ["バス", 40]),
      stop("15:00", "銀山温泉街", "川をはさんで木造の旅館が並ぶ通り。足湯や食べ歩きも楽しめます。", "ginzanOnsen", 38.5706, 140.5306, ["徒歩", 10]),
      stop("16:00", "白銀の滝", "温泉街の奥にある滝。遊歩道から間近に見られます。", null, 38.569, 140.533, ["徒歩", 10]),
      stop("17:30", "ガス灯の夜景", "日が落ちるとガス灯がともり、通りの雰囲気が変わります。写真は橋の上から。", null, 38.5704, 140.5312),
    ],
    travelerInfo: travelerInfo({ englishStaff: ["caution", "少なめ"], reservation: ["caution", "宿は必要"], vegetarian: ["caution", "事前に相談"] }),
    comments: [
      comment("Chloe", "2026.01.16", 22, "It looks exactly like the photos, especially in the snow. Rooms sell out months ahead."),
      comment("Lucas", "2026.01.14", 8, "Only a few buses per day from Oishida. We almost missed the last one."),
    ],
    prompt: "山形の銀山温泉で、温泉街の夜景と温泉を楽しみたい。1泊2日。車なし。",
  },
  {
    id: "kanazawa-chaya-garden",
    region: "石川",
    title: "金沢で出会う、茶屋街と庭園の1日",
    lead: "市場で海鮮、茶屋街で甘味、午後は庭園と美術館へ。バスと徒歩でまわれる金沢の定番ルートです。",
    image: "kanazawaChaya",
    daysLabel: "1日",
    durationLabel: "約7時間",
    budgetYen: 12000,
    transportLabel: "バス・徒歩",
    styles: ["ひとり旅", "家族"],
    tags: ["カフェ", "グルメ", "ひとり旅", "家族旅行"],
    author: "Lucas",
    postedOn: "2026.05.20",
    rating: 4.7,
    reviewCount: 68,
    likeCount: 312,
    stops: [
      stop("10:00", "近江町市場", "金沢の台所。海鮮丼や串焼きを少しずつ食べられます。", null, 36.5714, 136.656, ["バス", 10]),
      stop("11:30", "ひがし茶屋街", "格子戸の町家が続く通り。金箔のソフトクリームや和菓子のお店があります。", "kanazawaChaya", 36.5724, 136.6665, ["バス", 15]),
      stop("14:00", "兼六園", "季節ごとに表情が変わる庭園。高台からは街も見渡せます。", null, 36.5621, 136.6627, ["徒歩", 5]),
      stop("15:30", "金沢21世紀美術館", "無料で入れるエリアだけでも楽しめる現代美術館。", null, 36.5609, 136.6583),
    ],
    travelerInfo: travelerInfo({ englishStaff: ["ok", "多い"], luggage: ["ok", "問題なし"] }),
    comments: [
      comment("Mia", "2026.05.24", 12, "The loop bus day pass was worth it. Announcements were in English too."),
      comment("Jack", "2026.05.22", 6, "The swimming pool artwork at the museum needs a timed ticket. Reserve online."),
    ],
    prompt: "金沢で茶屋街と兼六園を1日でめぐりたい。車なし。",
  },
  {
    id: "furano-biei-drive",
    region: "北海道",
    title: "富良野・美瑛、花畑と青い池のドライブ",
    lead: "ラベンダー畑から丘の花畑、青い池へ。北海道らしい景色を車でつなぐ日帰りルートです。",
    image: "furanoLavender",
    daysLabel: "1日",
    durationLabel: "約8時間",
    budgetYen: 8000,
    transportLabel: "車",
    styles: ["カップル", "家族"],
    tags: ["北海道", "ドライブ", "カップル", "家族旅行"],
    author: "Ethan",
    postedOn: "2026.07.21",
    rating: 4.8,
    reviewCount: 55,
    likeCount: 211,
    stops: [
      stop("10:00", "ファーム富田", "7月はラベンダーが見ごろ。ラベンダー味のソフトクリームも人気です。", "furanoLavender", 43.4188, 142.4276, ["車", 30]),
      stop("11:30", "四季彩の丘", "丘一面に花の帯が広がる花畑。トラクターバスでも回れます。", "flowerHill", 43.5297, 142.4472, ["車", 30]),
      stop("13:30", "白金 青い池", "水の色が天気や季節で変わる池。駐車場から歩いて5分ほどです。", "bluePond", 43.4935, 142.6142, ["車", 35]),
      stop("15:30", "パッチワークの路", "畑が模様のように続く丘の道。畑には入らず、道路から眺めます。", "patchwork", 43.612, 142.43),
    ],
    travelerInfo: travelerInfo({ reservation: ["caution", "レンタカーは必要"], luggage: ["ok", "車なら問題なし"] }),
    comments: [
      comment("Olivia", "2026.07.25", 16, "The Blue Pond car park was full by noon. Go in the morning if you can."),
      comment("Noah", "2026.07.23", 7, "Please do not walk into the fields for photos. There are signs in English everywhere."),
    ],
    prompt: "札幌から車で富良野と美瑛へ。花畑と青い池をめぐる日帰りドライブをしたい。",
  },
  {
    id: "otaru-canal-evening",
    region: "北海道",
    title: "小樽運河と夕暮れさんぽ",
    lead: "駅前の市場で海鮮、ガラス工房の通りを歩いて、夕暮れの運河へ。半日でまわれる小樽のルートです。",
    image: "otaruWinter",
    daysLabel: "1日",
    durationLabel: "約4時間",
    budgetYen: 5000,
    transportLabel: "徒歩",
    styles: ["ひとり旅", "カップル"],
    tags: ["北海道", "グルメ", "カフェ", "ひとり旅"],
    author: "Chloe",
    postedOn: "2026.02.08",
    rating: 4.5,
    reviewCount: 42,
    likeCount: 189,
    stops: [
      stop("14:00", "小樽駅", "札幌から電車で約35分。駅を出ると坂の先に海が見えます。", null, 43.1977, 140.9937, ["徒歩", 2]),
      stop("14:15", "三角市場", "駅のすぐ隣の市場。小さめの海鮮丼を出すお店が並んでいます。", "kaisendon", 43.1983, 140.9945, ["徒歩", 15]),
      stop("15:30", "堺町通り", "ガラス工房やオルゴールのお店が続く通り。カフェでひと休みもできます。", null, 43.192, 141.007, ["徒歩", 12]),
      stop("17:00", "小樽運河", "夕暮れどきはガス灯と倉庫が水面に映ります。冬は足元が滑りやすいので注意。", "hero", 43.199, 141.002),
    ],
    travelerInfo: travelerInfo({ luggage: ["caution", "冬は雪道に注意"] }),
    comments: [
      comment("Liam", "2026.02.11", 11, "The canal at dusk was the highlight. Streets were icy, so wear proper shoes in winter."),
      comment("Emma", "2026.02.09", 4, "Coin lockers at Otaru Station were enough for two large suitcases."),
    ],
    prompt: "小樽で夕方から3時間、運河のあたりを歩いて楽しみたい。",
  },
];
